from enum import StrEnum


class ErrorCode(StrEnum):
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    PLACA_DUPLICADA = "PLACA_DUPLICADA"
    INVALID_UPDATE = "INVALID_UPDATE"
    FX_UNAVAILABLE = "FX_UNAVAILABLE"
